name: Testing

on:
  workflow_dispatch:
  push:

jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - name: stepA
      run: |
        exit 1

    - name: stepB
      #if: ${{ success() }}
      run: |
        echo "i am in step B"
